/**
 * Recipe service for Supabase CRUD operations.
 */

import { supabase } from '../../services/supabase';
import type { RecipeV2, CreateRecipeData, UpdateRecipeData } from './recipeTypesV2';

/**
 * Fetch all recipes for a user.
 * Returns recipes ordered by created_at descending (newest first).
 *
 * @param userId - The user's UUID
 * @returns Object with recipes array and optional error message
 */
export async function fetchRecipes(
  userId: string
): Promise<{ recipes: RecipeV2[]; error: string | null }> {
  try {
    const { data, error } = await supabase
      .from('recipes')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching recipes:', error);
      return { recipes: [], error: 'Failed to load recipes. Please try again.' };
    }

    return { recipes: data as RecipeV2[], error: null };
  } catch (err) {
    console.error('Unexpected error fetching recipes:', err);
    return { recipes: [], error: 'An unexpected error occurred. Please try again.' };
  }
}

/**
 * Fetch a single recipe by ID.
 *
 * @param id - The recipe UUID
 * @returns Object with recipe (or null) and optional error message
 */
export async function fetchRecipeById(
  id: string
): Promise<{ recipe: RecipeV2 | null; error: string | null }> {
  try {
    const { data, error } = await supabase
      .from('recipes')
      .select('*')
      .eq('id', id)
      .single();

    if (error) {
      if (error.code === 'PGRST116') {
        return { recipe: null, error: 'Recipe not found.' };
      }
      console.error('Error fetching recipe:', error);
      return { recipe: null, error: 'Failed to load recipe. Please try again.' };
    }

    return { recipe: data as RecipeV2, error: null };
  } catch (err) {
    console.error('Unexpected error fetching recipe:', err);
    return { recipe: null, error: 'An unexpected error occurred. Please try again.' };
  }
}

/**
 * Create a new recipe.
 * The user_id is set from the provided userId parameter.
 * Timestamps are auto-generated by Supabase.
 *
 * @param userId - The user's UUID
 * @param data - Recipe data to create
 * @returns Object with created recipe (or null) and optional error message
 */
export async function createRecipe(
  userId: string,
  data: CreateRecipeData
): Promise<{ recipe: RecipeV2 | null; error: string | null }> {
  try {
    const { data: recipe, error } = await supabase
      .from('recipes')
      .insert({
        user_id: userId,
        title: data.title,
        ingredients: data.ingredients,
        steps: data.steps,
        original_servings: data.original_servings,
        category: data.category,
        tags: data.tags,
        photo_url: data.photo_url,
        notes: data.notes,
      })
      .select()
      .single();

    if (error) {
      console.error('Error creating recipe:', error);
      return { recipe: null, error: 'Failed to save recipe. Please try again.' };
    }

    return { recipe: recipe as RecipeV2, error: null };
  } catch (err) {
    console.error('Unexpected error creating recipe:', err);
    return { recipe: null, error: 'An unexpected error occurred. Please try again.' };
  }
}

/**
 * Update an existing recipe.
 * Only updates provided fields (partial update supported).
 * The updated_at timestamp is auto-updated by Supabase.
 *
 * @param data - Recipe update data (must include id)
 * @returns Object with updated recipe (or null) and optional error message
 */
export async function updateRecipe(
  data: UpdateRecipeData
): Promise<{ recipe: RecipeV2 | null; error: string | null }> {
  try {
    const { id, ...updateFields } = data;

    const { data: recipe, error } = await supabase
      .from('recipes')
      .update({
        ...updateFields,
        updated_at: new Date().toISOString(),
      })
      .eq('id', id)
      .select()
      .single();

    if (error) {
      if (error.code === 'PGRST116') {
        return { recipe: null, error: 'Recipe not found.' };
      }
      console.error('Error updating recipe:', error);
      return { recipe: null, error: 'Failed to update recipe. Please try again.' };
    }

    return { recipe: recipe as RecipeV2, error: null };
  } catch (err) {
    console.error('Unexpected error updating recipe:', err);
    return { recipe: null, error: 'An unexpected error occurred. Please try again.' };
  }
}

/**
 * Delete a recipe by ID.
 *
 * @param id - The recipe UUID to delete
 * @returns Object with optional error message
 */
export async function deleteRecipe(
  id: string
): Promise<{ error: string | null }> {
  try {
    const { error } = await supabase
      .from('recipes')
      .delete()
      .eq('id', id);

    if (error) {
      console.error('Error deleting recipe:', error);
      return { error: 'Failed to delete recipe. Please try again.' };
    }

    return { error: null };
  } catch (err) {
    console.error('Unexpected error deleting recipe:', err);
    return { error: 'An unexpected error occurred. Please try again.' };
  }
}
