import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as Clipboard from 'expo-clipboard';
import type { Recipe } from './recipeTypes';
import { formatQuantity } from '../scaling/scaleIngredients';

/**
 * Formats an ingredient for display.
 *
 * @param quantity - The ingredient quantity
 * @param unit - Optional unit of measurement
 * @param label - The ingredient name
 * @returns Formatted ingredient string
 */
function formatIngredient(quantity: number, unit: string | undefined, label: string): string {
  const formattedQty = formatQuantity(quantity);
  if (unit) {
    return `${formattedQty} ${unit} ${label}`;
  }
  return `${formattedQty} ${label}`;
}

/**
 * Formats a recipe as plain text for sharing or clipboard.
 *
 * @param recipe - The recipe to format
 * @returns Formatted plain text string
 *
 * @example
 * const text = formatRecipeAsText(recipe);
 * // Returns:
 * // "Chocolate Cake
 * // Servings: 8
 * //
 * // Ingredients:
 * // - 2 cups flour
 * // - 1 cup sugar
 * // ..."
 */
export function formatRecipeAsText(recipe: Recipe): string {
  const lines: string[] = [];

  // Title
  lines.push(recipe.title);
  lines.push(`Servings: ${recipe.currentServings}`);
  lines.push('');

  // Ingredients
  lines.push('Ingredients:');
  for (const ingredient of recipe.ingredients) {
    const formatted = formatIngredient(ingredient.quantity, ingredient.unit, ingredient.label);
    lines.push(`- ${formatted}`);
  }

  return lines.join('\n');
}

/**
 * Generates HTML content for PDF export.
 *
 * @param recipe - The recipe to render as HTML
 * @returns HTML string for PDF generation
 */
function generateRecipeHtml(recipe: Recipe): string {
  const ingredientItems = recipe.ingredients
    .map((ing) => {
      const formatted = formatIngredient(ing.quantity, ing.unit, ing.label);
      return `<li style="margin-bottom: 8px;">${escapeHtml(formatted)}</li>`;
    })
    .join('\n      ');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(recipe.title)}</title>
</head>
<body style="font-family: system-ui, -apple-system, sans-serif; padding: 40px; max-width: 600px; margin: 0 auto; color: #333;">
  <h1 style="font-size: 28px; margin-bottom: 8px; color: #1a1a1a;">${escapeHtml(recipe.title)}</h1>
  <p style="font-size: 16px; color: #666; margin-bottom: 24px;">Servings: ${recipe.currentServings}</p>

  <h2 style="font-size: 20px; margin-bottom: 16px; color: #1a1a1a;">Ingredients</h2>
  <ul style="font-size: 16px; line-height: 1.6; padding-left: 20px;">
      ${ingredientItems}
  </ul>

  <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #999;">
    Generated by Recipe Scale
  </footer>
</body>
</html>`;
}

/**
 * Escapes HTML special characters to prevent XSS.
 *
 * @param text - Text to escape
 * @returns Escaped HTML string
 */
function escapeHtml(text: string): string {
  const htmlEntities: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  };
  return text.replace(/[&<>"']/g, (char) => htmlEntities[char] || char);
}

/**
 * Generates a PDF file from a recipe and returns the file URI.
 *
 * @param recipe - The recipe to convert to PDF
 * @returns Promise resolving to the PDF file URI
 * @throws Error if PDF generation fails
 *
 * @example
 * const fileUri = await generateRecipePdf(recipe);
 * console.log(`PDF saved to: ${fileUri}`);
 */
export async function generateRecipePdf(recipe: Recipe): Promise<string> {
  const html = generateRecipeHtml(recipe);

  const { uri } = await Print.printToFileAsync({
    html,
    base64: false,
  });

  return uri;
}

/**
 * Shares a recipe via the system share sheet.
 * On iOS/Android, this opens the native share dialog.
 *
 * @param recipe - The recipe to share
 * @throws Error if sharing is not available or fails
 *
 * @example
 * await shareRecipe(recipe);
 */
export async function shareRecipe(recipe: Recipe): Promise<void> {
  // Check if sharing is available
  const isAvailable = await Sharing.isAvailableAsync();

  if (!isAvailable) {
    // Fallback: copy to clipboard if sharing not available
    await copyRecipeToClipboard(recipe);
    throw new Error('Sharing not available. Recipe copied to clipboard instead.');
  }

  // Generate PDF for sharing
  const pdfUri = await generateRecipePdf(recipe);

  await Sharing.shareAsync(pdfUri, {
    mimeType: 'application/pdf',
    dialogTitle: `Share ${recipe.title}`,
    UTI: 'com.adobe.pdf',
  });
}

/**
 * Copies the recipe text to the system clipboard.
 *
 * @param recipe - The recipe to copy
 *
 * @example
 * await copyRecipeToClipboard(recipe);
 * // Recipe text is now in clipboard
 */
export async function copyRecipeToClipboard(recipe: Recipe): Promise<void> {
  const text = formatRecipeAsText(recipe);
  await Clipboard.setStringAsync(text);
}

/**
 * Shares recipe as plain text (alternative to PDF sharing).
 * Useful for messaging apps that prefer text over files.
 *
 * @param recipe - The recipe to share as text
 * @throws Error if sharing is not available
 */
export async function shareRecipeAsText(recipe: Recipe): Promise<void> {
  const isAvailable = await Sharing.isAvailableAsync();

  if (!isAvailable) {
    await copyRecipeToClipboard(recipe);
    throw new Error('Sharing not available. Recipe copied to clipboard instead.');
  }

  // For text sharing, we create a temporary text file
  const text = formatRecipeAsText(recipe);
  const html = `<pre style="font-family: monospace; white-space: pre-wrap;">${escapeHtml(text)}</pre>`;

  const { uri } = await Print.printToFileAsync({
    html,
    base64: false,
  });

  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: `Share ${recipe.title}`,
  });
}
